# Generated by Django 3.1.5 on 2021-01-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_manufacturer'),
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specs.ProductFeatures'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturer'),
        ),
    ]
